name: todo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.5
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^6.1.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.2.4+1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.6
  rxdart: ^0.27.7
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
